export const products = [
  {
    id: 1,
    title: 'Prueba POO TSs',
    price: 21,
    description: 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    category: {
      id: 2,
      name: 'Electronics',
      image: 'https://api.lorem.space/image/watch?w=640&h=480&r=3264',
    },
    images: [
      'https://api.lorem.space/image/watch?w=640&h=480&r=6893',
      'https://api.lorem.space/image/watch?w=640&h=480&r=6163',
      'https://api.lorem.space/image/watch?w=640&h=480&r=7377',
    ],
  },
  {
    id: 2,
    title: 'Handcrafted Fresh Bacon',
    price: 59,
    description: 'The Football Is Good For Training And Recreational Purposes',
    category: {
      id: 3,
      name: 'Furniture',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=3114',
    },
    images: [
      'https://api.lorem.space/image/furniture?w=640&h=480&r=4417',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=9041',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=1815',
    ],
  },
  {
    id: 3,
    title: 'Rustic Fresh Towels',
    price: 324,
    description: 'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    category: {
      id: 3,
      name: 'Furniture',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=3114',
    },
    images: [
      'https://api.lorem.space/image/furniture?w=640&h=480&r=3152',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=2364',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=2948',
    ],
  },
  {
    id: 4,
    title: 'Refined Wooden Chicken',
    price: 16,
    description: 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: {
      id: 3,
      name: 'Furniture',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=3114',
    },
    images: [
      'https://api.lorem.space/image/furniture?w=640&h=480&r=453',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=5949',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=2664',
    ],
  },
  {
    id: 5,
    title: 'Refined Steel Pizza',
    price: 290,
    description: 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    category: {
      id: 2,
      name: 'Electronics',
      image: 'https://api.lorem.space/image/watch?w=640&h=480&r=3264',
    },
    images: [
      'https://api.lorem.space/image/watch?w=640&h=480&r=3125',
      'https://api.lorem.space/image/watch?w=640&h=480&r=6382',
      'https://api.lorem.space/image/watch?w=640&h=480&r=4858',
    ],
  },
  {
    id: 6,
    title: 'Awesome Frozen Hat',
    price: 994,
    description: 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    category: {
      id: 1,
      name: 'Clothes',
      image: 'https://api.lorem.space/image/fashion?w=640&h=480&r=128',
    },
    images: [
      'https://api.lorem.space/image/fashion?w=640&h=480&r=451',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=1521',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=8508',
    ],
  },
  {
    id: 7,
    title: 'Refined Soft Cheese',
    price: 293,
    description: 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: {
      id: 4,
      name: 'Shoes',
      image: 'https://api.lorem.space/image/shoes?w=640&h=480&r=3146',
    },
    images: [
      'https://api.lorem.space/image/shoes?w=640&h=480&r=765',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=4512',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=1043',
    ],
  },
  {
    id: 8,
    title: 'Handcrafted Cotton Chicken',
    price: 787,
    description: 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    category: {
      id: 1,
      name: 'Clothes',
      image: 'https://api.lorem.space/image/fashion?w=640&h=480&r=128',
    },
    images: [
      'https://api.lorem.space/image/fashion?w=640&h=480&r=3418',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=7033',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=6861',
    ],
  },
  {
    id: 9,
    title: 'Sleek Concrete Salad',
    price: 7,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: {
      id: 4,
      name: 'Shoes',
      image: 'https://api.lorem.space/image/shoes?w=640&h=480&r=3146',
    },
    images: [
      'https://api.lorem.space/image/shoes?w=640&h=480&r=507',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=1223',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=5274',
    ],
  },
  {
    id: 10,
    title: 'Ergonomic Soft Gloves',
    price: 569,
    description: 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: {
      id: 1,
      name: 'Clothes',
      image: 'https://api.lorem.space/image/fashion?w=640&h=480&r=128',
    },
    images: [
      'https://api.lorem.space/image/fashion?w=640&h=480&r=8326',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=1584',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=5644',
    ],
  },
  {
    id: 11,
    title: 'Incredible Metal Computer',
    price: 896,
    description: 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: {
      id: 2,
      name: 'Electronics',
      image: 'https://api.lorem.space/image/watch?w=640&h=480&r=3264',
    },
    images: [
      'https://api.lorem.space/image/watch?w=640&h=480&r=6827',
      'https://api.lorem.space/image/watch?w=640&h=480&r=741',
      'https://api.lorem.space/image/watch?w=640&h=480&r=61',
    ],
  },
  {
    id: 12,
    title: 'Small Frozen Cheese',
    price: 702,
    description: 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    category: {
      id: 4,
      name: 'Shoes',
      image: 'https://api.lorem.space/image/shoes?w=640&h=480&r=3146',
    },
    images: [
      'https://api.lorem.space/image/shoes?w=640&h=480&r=2635',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=3161',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=6305',
    ],
  },
  {
    id: 13,
    title: 'Handmade Frozen Salad',
    price: 230,
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    category: {
      id: 3,
      name: 'Furniture',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=3114',
    },
    images: [
      'https://api.lorem.space/image/furniture?w=640&h=480&r=1485',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=9208',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=3178',
    ],
  },
  {
    id: 14,
    title: 'Incredible Frozen Pants',
    price: 349,
    description: 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: {
      id: 3,
      name: 'Furniture',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=3114',
    },
    images: [
      'https://api.lorem.space/image/furniture?w=640&h=480&r=2546',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=2628',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=653',
    ],
  },
  {
    id: 15,
    title: 'Sleek Metal Bike',
    price: 83,
    description: 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    category: {
      id: 4,
      name: 'Shoes',
      image: 'https://api.lorem.space/image/shoes?w=640&h=480&r=3146',
    },
    images: [
      'https://api.lorem.space/image/shoes?w=640&h=480&r=591',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=7185',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=2016',
    ],
  },
  {
    id: 16,
    title: 'Fantastic Frozen Chips',
    price: 163,
    description: 'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    category: {
      id: 4,
      name: 'Shoes',
      image: 'https://api.lorem.space/image/shoes?w=640&h=480&r=3146',
    },
    images: [
      'https://api.lorem.space/image/shoes?w=640&h=480&r=8160',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=7854',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=564',
    ],
  },
  {
    id: 17,
    title: 'Small Steel Chair',
    price: 779,
    description: 'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    category: {
      id: 1,
      name: 'Clothes',
      image: 'https://api.lorem.space/image/fashion?w=640&h=480&r=128',
    },
    images: [
      'https://api.lorem.space/image/fashion?w=640&h=480&r=1321',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=4884',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=4978',
    ],
  },
  {
    id: 18,
    title: 'Handmade Steel Chair',
    price: 278,
    description: 'The Football Is Good For Training And Recreational Purposes',
    category: {
      id: 2,
      name: 'Electronics',
      image: 'https://api.lorem.space/image/watch?w=640&h=480&r=3264',
    },
    images: [
      'https://api.lorem.space/image/watch?w=640&h=480&r=5609',
      'https://api.lorem.space/image/watch?w=640&h=480&r=8838',
      'https://api.lorem.space/image/watch?w=640&h=480&r=728',
    ],
  },
  {
    id: 19,
    title: 'Handmade Wooden Computer',
    price: 516,
    description: 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    category: {
      id: 5,
      name: 'Others',
      image: 'https://api.lorem.space/image?w=640&h=480&r=5275',
    },
    images: [
      'https://api.lorem.space/image?w=640&h=480&r=1815',
      'https://api.lorem.space/image?w=640&h=480&r=1382',
      'https://api.lorem.space/image?w=640&h=480&r=7753',
    ],
  },
  {
    id: 20,
    title: 'Gorgeous Fresh Salad',
    price: 462,
    description: 'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    category: {
      id: 2,
      name: 'Electronics',
      image: 'https://api.lorem.space/image/watch?w=640&h=480&r=3264',
    },
    images: [
      'https://api.lorem.space/image/watch?w=640&h=480&r=2269',
      'https://api.lorem.space/image/watch?w=640&h=480&r=7090',
      'https://api.lorem.space/image/watch?w=640&h=480&r=2760',
    ],
  },
  {
    id: 21,
    title: 'Rustic Metal Car',
    price: 573,
    description: "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    category: {
      id: 4,
      name: 'Shoes',
      image: 'https://api.lorem.space/image/shoes?w=640&h=480&r=3146',
    },
    images: [
      'https://api.lorem.space/image/shoes?w=640&h=480&r=1077',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=1273',
      'https://api.lorem.space/image/shoes?w=640&h=480&r=5700',
    ],
  },
  {
    id: 22,
    title: 'Unbranded Granite Hat',
    price: 500,
    description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    category: {
      id: 3,
      name: 'Furniture',
      image: 'https://api.lorem.space/image/furniture?w=640&h=480&r=3114',
    },
    images: [
      'https://api.lorem.space/image/furniture?w=640&h=480&r=7691',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=7879',
      'https://api.lorem.space/image/furniture?w=640&h=480&r=4404',
    ],
  },
  {
    id: 23,
    title: 'Incredible Concrete Hat',
    price: 840,
    description: 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    category: {
      id: 1,
      name: 'Clothes',
      image: 'https://api.lorem.space/image/fashion?w=640&h=480&r=128',
    },
    images: [
      'https://api.lorem.space/image/fashion?w=640&h=480&r=571',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=6968',
      'https://api.lorem.space/image/fashion?w=640&h=480&r=5165',
    ],
  },
];
